# Fichier de configuration pour Netlify (version asynchrone)

[build]
  # Indique à Netlify où trouver les fichiers de fonctions
  functions = "netlify/functions"

# On spécifie que la fonction "initiate-analysis" doit avoir un timeout étendu
# 900 secondes = 15 minutes, le maximum pour une fonction d'arrière-plan
[functions."initiate-analysis"]
  timeout = 900

[[redirects]]
  # Cette règle redirige tous les appels API vers nos fonctions
  from = "/graph/api/*"
  to = "/.netlify/functions/:splat"
  status = 200