[build]
  # On ne spécifie PAS de dossier de publication ici,
  # pour que la racine de votre projet soit publiée.
  functions = "netlify/functions"

[[redirects]]
  # La redirection ne s'active que pour les appels
  # provenant du sous-dossier /graph/
  from = "/graph/api/*"
  to = "/.netlify/functions/:splat"
  status = 200