# This file tells Netlify how to build your site.
# It specifies where the serverless functions are located.
[build]
  # Directory where your serverless functions are located
  functions = "netlify/functions/"
